Make resolveAddr more strict.
Go's net.ResolveTCPAddr allows an empty host or port part, returning for
them nil and 0 respectively. It will also resolve names, which I don't
think we need so we should avoid it for now.

These are the test failures that this change fixes:
--- FAIL: TestResolveAddr (0.00 seconds)
        pt_test.go:201: "" unexpectedly succeeded: "<nil>:0"
        pt_test.go:201: "1.2.3.4:" unexpectedly succeeded: "1.2.3.4:0"
        pt_test.go:201: ":9999" unexpectedly succeeded: "<nil>:9999"
        pt_test.go:201: "[1:2::3:4]:" unexpectedly succeeded: "[1:2::3:4]:0"
        pt_test.go:201: "localhost:9999" unexpectedly succeeded: "127.0.0.1:9999"
        pt_test.go:201: "[localhost]:9999" unexpectedly succeeded: "127.0.0.1:9999"